[package]
name = "chip8"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.0"

[target.'cfg(not(windows))'.dependencies.sdl2]
version = "0.35"

[target.'cfg(windows)'.dependencies.sdl2]
version = "0.35"
features = ["bundled"]
