[package]
name = "chip8"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.0"

[target.'cfg(unix)'.dependencies.sdl2]
version = "*"

[target.'cfg(windows)'.dependencies.sdl2]
version = "*"
features = ["bundled"]
